services:
  mysql:
    container_name: mysqlcontainer
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: jwtsecuritybd
    ports:
      - "3311:3306"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - spring-boot-net
  spring-boot-app:
    container_name: springDemoPipeline
    image: spring-boot-pipeline
    ports:
      - "8011:8080"
    networks:
      - spring-boot-net
    depends_on:
      - mysql

volumes:
  mysql:

networks:
  spring-boot-net:
    driver: bridge
    external: true



